### ISSUE TITLE
Unable to load local XML file into action

### ISSUE THREAD

**Issue by adithyaamara** [Mudlet/xmlstarlet-action#10]
Issue:  `xmstartlet` action gives me error while trying to load a XML file from local actions workspace. [File Exists]
> The XML file is a python coverage report.

Snippet Used: 
```
uses: Mudlet/xmlstarlet-action@master
        id: xmledit
        with:
          args: ed -u "<an xml path>" -v "<value to be replace in said path>" myfile.xml
```
Error Thrown:
```
Error: Unable to process file command 'output' successfully.
Error: Invalid format '  <!-- Generated by coverage.py: https://coverage.readthedocs.io/ -->'
```
Same is working fine while local testing using linux wsl terminal's xmlstarlet command downloaded from apt.

PS: I am unable to apt install `xmlstarlet` in runner because of permission issues.

Kindly help!

**Comment by adithyaamara** [comment]
Found the right syntax for using the action, by referring to other repos which are using the same action.

Right usage:
```
uses:
  Mudlet/xmlstarlet-action@v1.1
    with: 
      args: ed -L --update "<an xml path>" -v "<value to be replace in said path>" "myfile.xml" 
```

1. -L for modifying the XML file in place.(One can use any extra flags that are available in regular xmlstarlet package)
2. The file name (myfile.xml) should be supplied as a string.

This is the only good XML editer GitHub action I have found so far. Some extra documentation on usage of action is appreciated.
